spring:
  application:
    name: spring-boot-actuator

  mail:
    host: smtp.gmail.com
    port: 587
    username: "lyhou282@gmail.com"
    password: "nizm fijt ltqk mtfi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: '/'

    #configuration mailsender


