server:
  port: 8888
file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: "lyhou282@gmail.com"
    password: "nizm fijt ltqk mtfi"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#config swagger ui
springdoc:
  swagger-ui:
    path: /

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE



# This is for the access token
ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key
